# -*- coding: utf-8 -*-
"""DEV_21AIB63

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3G71KiQ1R_5JGNbOn5sQuYwXSttFG5H
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/International_Report_Passengers.csv')
df1=df.head(500)

df1.describe()

df1.info()

df1.shape

df1.nunique()

df1.isnull().sum()

df1.loc[df1["airlineid"] == 20414, "carrier"] = 'OW'
df1.loc[df1["airlineid"] == 20415, "carrier"] = 'XG'

df1.isnull().sum()

"""**VISUALIZATION**"""

plt.bar(df1['usg_wac'],df1['fg_wac'], label="red Bar" ,color='r')
plt.xlabel("usg_wac")
plt.ylabel("fg_wac")
plt.title("International Report Passengers")
plt.legend()
plt.show

df1.plot.area()

plt.hist(df1['usg_wac'],color='green')
plt.title('usg_wac histogram')

sns.displot(df1['Month'],bins=100)

sns.heatmap(df1.corr())

df1.plot(kind="scatter",x="airlineid",y="fg_wac")

df1.plot.box(vert=False)

x=df1.usg_wac
plt.pie(x)
plt.show()

plt.polar(x)
plt.show()

